# Autogenerated wrapper script for very_nauty_jll for x86_64-w64-mingw32
export libvn_graph

JLLWrappers.@generate_wrapper_header("very_nauty")
JLLWrappers.@declare_library_product(libvn_graph, "libvn_graph.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libvn_graph,
        "bin\\libvn_graph.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
